<?php

if (!isset($_SESSION["auth"])) {
  header('location:index.php?goto=login&target=login');
  exit();
}

use controller\crypt;
?>
<!DOCTYPE html>
<html lang="fr">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>VDATA Admin Dashboard</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="../assets/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="../assets/vendors/iconfonts/flag-icon-css/css/flag-icon.min.css">
  <link rel="stylesheet" href="../assets/vendors/iconfonts/simple-line-icon/css/simple-line-icons.css">
  <link rel="stylesheet" href="../assets/vendors/css/vendor.bundle.base.css">
  <link rel="stylesheet" href="../assets/vendors/css/vendor.bundle.addons.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="../assets/css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="../assets/images/Vipp-Data.png" />
  <style>
    #user_dash{
      margin:1rem  0 auto ;
      text-align:center;
      display: flex;
      justify-content: center;
  }

  #flag{
    width:1.6rem;
    height:1.6rem;
  }

  .token{
    margin-left: 2rem;
    font-size: 1.5rem;
  }

  .token span{
    background-color: #F9322C;
    color: white;
    padding: 0.4rem;
    border-radius: 50%;
  }

  </style>
</head>

<body>
  <div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">

        <a class="navbar-brand brand-logo" href="index.php?goto=
                  <?= $this->datacrypt('dashboard') ?>&target=<?= $this->datacrypt('dashboard') ?>">
          <img src="../assets/images/Vipp-Data.png" id="vdata_log" alt="logo" />
        </a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
          <span class="mdi  mdi-menu"></span>
        </button>

        <?php 
        if(isset($_GET['data_type'])){
          if($this->datadecrypt($_GET['data_type']) == 'data_collected'){ ?>
            <img src="../assets/images/facebook.png" class="flag-icon" id="flag" alt="">
              Facebook
          <?php } else if($this->datadecrypt($_GET['data_type']) == 'data_collected_tiktok'){ ?>
            <img src="../assets/images/tik-tok.png" class="flag-icon" id="flag" alt="">
              Tiktok
          <?php } else { ?>
            <img src="../assets/images/facebook.png" class="flag-icon" id="flag" alt="">
              Facebook
        <?php } } ?>
        
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item search-wrapper d-none d-md-block">
            <form action="#">
              <div class="form-group mb-0">
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <!-- <i class="mdi mdi-magnify"></i> -->
                    </span>
                  </div>
                  <!-- <input type="text" class="form-control" placeholder="Search"> -->
                </div>
              </div>
            </form>
          </li>
          <li class="nav-item dropdown d-none d-xl-inline-block user-dropdown">
            <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <div class="dropdown-toggle-wrapper">
                <div class="inner">
                  <img class="img-xs rounded-circle" src="../assets/images/admin_image.jpg" alt="Profile image">
                </div>
                <div class="inner user_prof">
                  <div class="inner">
                    <span class="profile-text font-weight-bold bold">
                      <?php echo ($adminUsername['pseudo']) ?>
                    </span>
                    <small class="profile-text small"><?php echo ($adminUsername['user_role'])?></small>
                  </div>

                  <div class="inner">
                    <div class="icon-wrapper">
                      <i class="mdi mdi-chevron-down"></i>
                    </div>
                  </div>

                </div>
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
            
              <a class="dropdown-item" id="user_dash" href="index.php?goto= <?=$this->datacrypt('dashboard')?>&target=<?=$this->datacrypt('disconnect')?>">
                Deconnexion
              </a>
            </div>

        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_settings-panel.html -->
      <div class="theme-setting-wrapper">
        <div id="theme-settings" class="settings-panel">
          <i class="settings-close mdi mdi-close"></i>
          <div class="d-flex align-items-center justify-content-between border-bottom">
            <p class="settings-heading font-weight-bold border-top-0 mb-3 pl-3 pt-0 border-bottom-0 pb-0">Template Skins</p>
          </div>
          <div class="sidebar-bg-options" id="sidebar-light-theme">
            <div class="img-ss rounded-circle bg-light border mr-3"></div>Light
          </div>
          <div class="sidebar-bg-options selected" id="sidebar-dark-theme">
            <div class="img-ss rounded-circle bg-dark border mr-3"></div>Dark
          </div>
          <p class="settings-heading font-weight-bold mt-2">Header Skins</p>
          <div class="color-tiles mx-0 px-4">
            <div class="tiles primary"></div>
            <div class="tiles success"></div>
            <div class="tiles warning"></div>
            <div class="tiles danger"></div>
            <div class="tiles pink"></div>
            <div class="tiles info"></div>
            <div class="tiles dark"></div>
            <div class="tiles default"></div>
          </div>
        </div>
      </div>
      <!-- partial -->
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas sidebar-dark" id="sidebar">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="index.php?goto=
                  <?= $this->datacrypt('dashboard') ?>&target=<?= $this->datacrypt('dashboard')?>&data_type=<?=$this->datacrypt('data_collected')?>">
              <i class="menu-icon icon-diamond"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#tables" aria-expanded="false" aria-controls="tables">
              <i class="menu-icon icon-grid"></i>
              <span class="menu-title">Data</span>
            </a>
            <div class="collapse" id="tables">
              <ul class="nav flex-column sub-menu">
              <li class="nav-item">
                  <a class="nav-link" href="index.php?goto=
                  <?=$this->datacrypt('dashboard')?>&target=<?=$this->datacrypt('table')?>&data_type=<?=$this->datacrypt('data_collected')?>">Facebook Data table</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="index.php?goto=
                  <?=$this->datacrypt('dashboard')?>&target=<?=$this->datacrypt('table')?>&data_type=<?=$this->datacrypt('data_collected_tiktok')?>">Tiktok Data table</a>
                </li>

              </ul>
            </div>
          </li>


          <?php if(isset($_SESSION["auth"])):?>
          <?php if($adminUsername['user_role']=="admin"):?>
          <li class="nav-item">
            <a class="nav-link" href="index.php?goto= <?=$this->datacrypt('login')?>&target=<?=$this->datacrypt('ajout')?>"><i class="menu-icon  icon-user"></i><span class="menu-title">Ajout utilisateur</span></a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="index.php?goto= <?=$this->datacrypt('users')?>&target=<?=$this->datacrypt('list')?>"><i class="menu-icon  icon-lock"></i><span class="menu-title">Gestion utilisateur</span></a>
          </li>
          <?php endif?>
          <?php endif?>


        </ul>
      </nav>
      <!-- partial -->
      
      <div class="main-panel">
        
        <div class="content-wrapper">
          <div class="card">
            
            <div class="card-body">
              
            <?php 
              if(isset($_GET['data_type'])){
                if($this->datadecrypt($_GET['data_type']) == 'data_collected'){ ?>
                  <h4 class="card-title surlign">Data facebook table</h4>
                <?php } else if($this->datadecrypt($_GET['data_type']) == 'data_collected_tiktok'){ ?>
                  <h4 class="card-title surlign">Data tiktok table</h4>
                <?php } else{ ?>
                  <h4 class="card-title surlign">Data facebook table</h4>
              <?php } } ?>

              <div class="row">
              <div id="date">
                <div class="wrapper mr-4 d-none d-sm-block" >

                  <?php
                      if(isset($_GET['data_type'])){
                        if($this->datadecrypt($_GET['data_type']) == 'data_collected'){ ?>
                          <form action="index.php?goto= 
                            <?= $this->datacrypt('dashboard') ?>
                                    &target= <?= $this->datacrypt('select') ?>&data_type=<?=$this->datacrypt('data_collected')?>"
                                  method="POST">
                              <label for="date_debut" class="mb-0"> Début: </label>
                              <input 
                              type="datetime-local" 
                              name="date_debut" 
                              step="1" 
                              value=<?php 
                                if(isset($_POST['valider']))  {
                                    echo $date_debut;
                                }else{
                                  echo "";
                                }
                                
                                ?>
                              >
                              <label for="date_fin" class="mb-0"> Fin: </label>
                              <input type="datetime-local" name="date_fin" step="1"
                              value=<?php 
                                if(isset($_POST['valider']))  {
                                    echo $date_fin;
                                }else{
                                  echo "";
                                }
                                
                                ?>
                              >
                              <button name="valider" class="btn btn-link btn-sm font-weight-bold">Valider</button>
                              <button id="btn_export" name="export" class="btn btn-link btn-sm font-weight-bold">
                              <i class="icon-share-alt"></i>Export</button>
                              <span class="token">Le token expire dans : 
                                <span>

                                <span id="jo">j</span>
                                <span id="he">h</span>
                                <span id="mi">m</span>
                                <span id="se"> s</span>
                                
                              </span>
                                
                              </span>
                          </form>
                          
                  <?php } else if($this->datadecrypt($_GET['data_type']) == 'data_collected_tiktok'){ ?>
                          <form action="index.php?goto= 
                              <?= $this->datacrypt('dashboard') ?>
                                      &target= <?= $this->datacrypt('select') ?>
                                      &data_type=<?=$this->datacrypt('data_collected_tiktok')?>"
                                    method="POST">
                                <label for="date_debut" class="mb-0"> Début: </label>
                                <input 
                                type="datetime-local" 
                                name="date_debut" 
                                step="1" 
                                value=<?php 
                                  if(isset($_POST['valider']))  {
                                      echo $date_debut;
                                  }else{
                                    echo "";
                                  }
                                  
                                  ?>
                                >
                                <label for="date_fin" class="mb-0"> Fin: </label>
                                <input type="datetime-local" name="date_fin" step="1"
                                value=<?php 
                                  if(isset($_POST['valider']))  {
                                      echo $date_fin;
                                  }else{
                                    echo "";
                                  }
                                  
                                  ?>
                                >
                                <button name="valider" class="btn btn-link btn-sm font-weight-bold">Valider</button>
                                <button id="btn_export" name="export" class="btn btn-link btn-sm font-weight-bold">
                                <i class="icon-share-alt"></i>Export</button>
                                <span class="token">Le token expire dans : 
                                <span>

                                <span id="jo">j</span>
                                <span id="he">h</span>
                                <span id="mi">m</span>
                                <span id="se"> s</span>
                                
                              </span>
                                
                              </span>
                            </form>

                          
                          <?php } else { ?>

                            <form action="index.php?goto= 
                            <?= $this->datacrypt('dashboard') ?>
                                    &target= <?= $this->datacrypt('select') ?>&data_type=<?=$this->datacrypt('data_collected')?>"
                                  method="POST">
                              <label for="date_debut" class="mb-0"> Début: </label>
                              <input 
                              type="datetime-local" 
                              name="date_debut" 
                              step="1" 
                              value=<?php 
                                if(isset($_POST['valider']))  {
                                    echo $date_debut;
                                }else{
                                  echo "";
                                }
                                
                                ?>
                              >
                              <label for="date_fin" class="mb-0"> Fin: </label>
                              <input type="datetime-local" name="date_fin" step="1"
                              value=<?php 
                                if(isset($_POST['valider']))  {
                                    echo $date_fin;
                                }else{
                                  echo "";
                                }
                                
                                ?>
                              >
                              <button name="valider" class="btn btn-link btn-sm font-weight-bold">Valider</button>
                              <button id="btn_export" name="export" class="btn btn-link btn-sm font-weight-bold">
                              <i class="icon-share-alt"></i>Export</button>
                          </form>
                          
                    <?php } } ?>
                </div>
     
                </div>
                <div class="col-12 table-responsive">
                  
                  <table id="order-listing" class="table tb">
                    <thead>
                      <tr>
                        <th>Formulaire</th>
                        <th>Adset_name</th>
                        <th>Campagne</th>
                        <th>Leadgen_id</th>
                        <th>Fai_actuel</th>
                        <th>Fai_actuel_val</th>
                        <th>Code_postal</th>
                        <th>Email</th>
                        <th>Telephone</th>
                        <th>retour_api</th>
                        <th>code_retour_api</th>
                        <th>Callback_time</th>
                        <th>Status</th>
                        <th>created_at</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($data as $key => $value) { ?>

                        <tr>
                          <td><?= $data[$key]['formulaire'] ?></td>
                          <td><?= $data[$key]['adset_name'] ?></td>
                          <td><?= $data[$key]['campagne'] ?></td>
                          <td><?= $data[$key]['leadgen_id'] ?></td>
                          <td><?= $data[$key]['fai_actuel'] ?></td>
                          <td><?= $data[$key]['fai_actuel_val'] ?></td>
                          <td><?= $data[$key]['code_postal'] ?></td>
                          <td><?= $data[$key]['email'] ?></td>
                          <td><?= $data[$key]['telephone'] ?></td>
                          <td><?= $data[$key]['retour_api'] ?></td>
                          <td><?= $data[$key]['code_retour_api'] ?></td>
                          <td>
                            <?php
                            if (isset($data[$key]['callback_time'])) {
                              echo "no calling time";
                            } else {
                              // echo  $data[$key]['callback_time']; 
                              echo "no calling time";
                            }
                            ?>
                          </td>

                          <td>
                            <label class="badge badge-info"><?= $data[$key]['status'] ?></label>
                          </td>
                          <td>
                            <button class="btn btn-outline-primary"><?= $data[$key]['created_at'] ?></button>
                          </td>
                        </tr>


                      <?php } ?>

                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:../../partials/_footer.html -->
        <footer class="footer">
          <div class="container-fluid clearfix">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2023
              <a href="">VippData</a>. All rights reserved.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Statistics
              <i class="mdi mdi-heart-outline text-danger"></i>
            </span>
          </div>
        </footer>
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

  <!-- plugins:js -->
  <script src="../assets/vendors/js/vendor.bundle.base.js"></script>
  <script src="../assets/vendors/js/vendor.bundle.addons.js"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="../assets/js/off-canvas.js"></script>
  <script src="../assets/js/hoverable-collapse.js"></script>
  <script src="../assets/js/misc.js"></script>
  <script src="../assets/js/settings.js"></script>
  <script src="../assets/js/todolist.js"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="../assets/js/dashboard.js"></script>
  <!-- End custom js for this page-->
  <script src="../assets/js/data-table.js"></script>

  <script>
    //Stockage du token actuel dans une variable
    let token_actuel= 5183795;
    //Convertion en timestamps de la date d'acquisition du token
    let date_acquisition = new Date('April 17, 2023 00:00:00');
    let timestamp_date_acquisition = date_acquisition.getTime() / 1000;
    //Additionner la date actuelle en timestamps et le token actuel
    let timest_expiry= timestamp_date_acquisition+token_actuel;
    
    let he = document.getElementById('he');
    let jo = document.getElementById('jo');
    let mi = document.getElementById('mi');
    let se = document.getElementById('se');

    // créer un objet Date à partir du timestamp (en millisecondes)
    let dates = new Date(timest_expiry * 1000);
  
   // définir la date de fin
    let date_fin = dates.getTime();

    // mettre à jour le compte à rebours toutes les secondes
    let interval = setInterval(function() {

      // obtenir la date et l'heure actuelles
      let maintenant = new Date().getTime();

      // calculer la différence entre la date de fin et la date actuelle
      let difference = date_fin - maintenant;

      // calculer les jours, les heures, les minutes et les secondes restantes
      let jours = Math.floor(difference / (1000 * 60 * 60 * 24));
      let heures = Math.floor((difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      let minutes = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60));
      let secondes = Math.floor((difference % (1000 * 60)) / 1000);

      // afficher le compte à rebours dans le DOM
      jo.innerText= jours  + "j :";
      he.innerText=heures + "h :" ;
      mi.innerText=minutes + "m :";
      se.innerText=secondes + "s";
      // si la date de fin est atteinte, afficher un message et arrêter le compte à rebours
      if (difference < 0) {
        clearInterval(interval);
        console.log("Le compte à rebours est terminé !");
      }
    }, 1000);
  </script>
</body>

</html>