<?php
$_ENV['database']='vippdata';
$_ENV['server']='localhost';
$_ENV['user']='si-dev-vipp';
$_ENV['password']='SI-dev-vipp123!!';
$_ENV['users']='root';
$_ENV['passwords']='';
$_ENV['host']='localhost';
$_ENV['bdd']='vdata';
$_ENV['FIRSTKEY']='Lk5Uz3slx3BrAghS1aaW5AYgWZRV0tIX5eI0yPchFz4=';
$_ENV['SECONDKEY']='EZ44mFi3TlAey1b2w4Y7lVDuqO+SRxGXsa7nctnr/JmMrA2vN6EJhrvdVZbxaQs5jpSe34X3ejFK/o9+Y5c83w===';
