<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>connexion</title>
    <link rel="stylesheet" href="../../assets/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../assets/vendors/iconfonts/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="../../assets/vendors/iconfonts/simple-line-icon/css/simple-line-icons.css">
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.addons.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="../../assets/vendors/icheck/skins/all.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="../../assets/css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="../assets/images/Vipp-Data.png" />
</head>

<body>
    <div class="card-body">
        <h4 class="card-title">Connexion</h4>

        <form class="forms-sample" action="" method="POST">
           
            <div class="form-group">
                <label for="user_name">User_name</label>
                <input type="text" name="user_name" id="user_name" class="form-control" placeholder="User_name">
            </div>
            <div class="form-group">
                <label for="user_surname">User_surname</label>
                <input type="text" name="user_surname" id="user_surname" class="form-control" placeholder="User_surname">
            </div>
            <div class="form-group">
                <label for="pseudo"> Pseudo:</label>
                <input type="text" name="pseudo" id="pseudo" class="form-control" placeholder="Entrer Pseudo">
            </div>
            <div class="form-group">
                <label for="_password">Password</label>
                <input type="password" name="_password" id="_password" class="form-control" placeholder="Password">
            </div>
            <div class="form-group">
                <label for="user_role">User_role</label>
                <input type="text" name="user_role" id="user_role" class="form-control" placeholder="user_role">
            </div>
           
            <button type="submit" class="btn btn-success mr-2">S'inscrire</button>
            <button class="btn btn-light">Annuler</button>
        </form>
    </div>
 <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="../../assets/vendors/js/vendor.bundle.base.js"></script>
  <script src="../../assets/vendors/js/vendor.bundle.addons.js"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="../../assets/js/off-canvas.js"></script>
  <script src="../../assets/js/hoverable-collapse.js"></script>
  <script src="../../assets/js/misc.js"></script>
  <script src="../../assets/js/settings.js"></script>
  <script src="../../assets/js/todolist.js"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="../../assets/js/file-upload.js"></script>
  <script src="../../assets/js/iCheck.js"></script>
  <script src="../../assets/js/typeahead.js"></script>
  <script src="../../assets/js/select2.js"></script>
  <!-- End custom js for this page-->
</body>

</html>