<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>vipp data Admin Dashboard</title>
  <link rel="stylesheet" href="../../assets/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="../../assets/vendors/iconfonts/flag-icon-css/css/flag-icon.min.css">
  <link rel="stylesheet" href="../../assets/vendors/iconfonts/simple-line-icon/css/simple-line-icons.css">
  <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css">
  <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.addons.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <link rel="stylesheet" href="../../assets/vendors/icheck/skins/all.css">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="../../assets/css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="../assets/images/Vipp-Data.png" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth register-bg-1 theme-one">
        <div class="row w-100 mx-auto">
          <div class="col-lg-4 mx-auto">
            <h2 class="text-center text-primary mb-4">Ajout d'utilisateur</h2>
            <div class="auto-form-wrapper">
              <form action=" " method="POST">
                <div class="form-group">
                  <div class="input-group">
                    <input type="text" name="user_name" id="user_name" class="form-control" placeholder="Nom">
                    <div class="input-group-append">

                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">

                    <input type="text" name="user_surname" id="user_surname" class="form-control" placeholder="Prénoms">
                   
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">

                    <input type="text" name="pseudo" id="pseudo" class="form-control" placeholder="Entrer Pseudo">
                   
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">

                    <input type="password" name="_password" id="_password" class="form-control" placeholder="Password">
                    
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">

                  <input type="text" name="user_role" id="user_role" class="form-control" placeholder="user_role">
                   
                  </div>
                </div>
                <div class="form-group">
                  <button class="btn btn-primary submit-btn btn-block" type="submit">S'inscrire</button>
                </div>
              </form>
              <?php if(isset($_GET['invalid'])) {?>
                    <div class="auth_check">
                        <img width="30px" height="30px" src="../../assets/images/images.jpeg" alt="">
                        <span class="text-center text-danger mb-4">Ce pseudo est déjà utilisé</span>
                    </div>       
                <?php }?>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="../../assets/vendors/js/vendor.bundle.base.js"></script>
  <script src="../../assets/vendors/js/vendor.bundle.addons.js"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="../../assets/js/off-canvas.js"></script>
  <script src="../../assets/js/hoverable-collapse.js"></script>
  <script src="../../assets/js/misc.js"></script>
  <script src="../../assets/js/settings.js"></script>
  <script src="../../assets/js/todolist.js"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="../../assets/js/file-upload.js"></script>
  <script src="../../assets/js/iCheck.js"></script>
  <script src="../../assets/js/typeahead.js"></script>
  <script src="../../assets/js/select2.js"></script>
  <!-- End custom js for this page-->
</body>

</html>